### ISSUE TITLE
v 0.8 full critical bug

### ISSUE THREAD

**Issue by sh1ny** [Daylily-Zeleen/HierarchicalFiniteStateMachine#2] opened 2022-10-18 19:57 UTC
Hey,

I just bought the full version from godotmarketplace and there's a critical bug with godot 3.5.1.
When you attach scripts to states, whenever you click a state, the script gets reverted to the last loaded version.
That happens to me on the demo project, here's examples:

First step:

I have the idle state selected and the idle script opened.

https://i.imgur.com/hcE39iV.png

Second step :

I edit the script and save:

https://i.imgur.com/v2XJOQT.png

I click on the jump state. Notice the script has reverted back:

https://i.imgur.com/fdyiSxJ.png

Any help would be appreciated.

**Comment by sh1ny** [comment] 2022-10-18 21:37
Also it works fine with 0.9 from this repo

**Comment by Daylily-Zeleen** [comment] 2022-10-19 02:46
> 嘿，
> 
> 我刚从 godotmarketplace 购买了完整版，godot 3.5.1 有一个严重的错误。 当您将脚本附加到状态时，每当您单击状态时，脚本都会恢复为上次加载的版本。 我在演示项目中遇到了这种情况，以下是示例：
> 
> 第一步：
> 
> 我选择了空闲状态并打开了空闲脚本。
> 
> https://i.imgur.com/hcE39iV.png
> 
> 第二步 ：
> 
> 我编辑脚本并保存：
> 
> https://i.imgur.com/v2XJOQT.png
> 
> 我点击跳转状态。请注意脚本已恢复：
> 
> https://i.imgur.com/fdyiSxJ.png
> 
> 任何帮助，将不胜感激。

Thanks for your support. Please give me some time to find out the reson of this bug.

**Comment by Daylily-Zeleen** [comment] 2022-10-19 02:52
> 嘿，
> 
> 我刚从 godotmarketplace 购买了完整版，godot 3.5.1 有一个严重的错误。 当您将脚本附加到状态时，每当您单击状态时，脚本都会恢复为上次加载的版本。 我在演示项目中遇到了这种情况，以下是示例：
> 
> 第一步：
> 
> 我选择了空闲状态并打开了空闲脚本。
> 
> https://i.imgur.com/hcE39iV.png
> 
> 第二步 ：
> 
> 我编辑脚本并保存：
> 
> https://i.imgur.com/v2XJOQT.png
> 
> 我点击跳转状态。请注意脚本已恢复：
> 
> https://i.imgur.com/fdyiSxJ.png
> 
> 任何帮助，将不胜感激。

Could you recod a video to demo how this bug occur?

I can't reproduce this bug by your description.

**Comment by sh1ny** [comment] 2022-10-19 12:31
Hello !

Steps to reproduce this:
I created a brand new project, copied the addon from the zip and enabled it.
Then i created a KinematicBody2D and attached HFSM to it.
Creating entry and 2 normal states. Then creating and attaching 2 scripts to State1 and State2 and writing some text in there.
Saving everything a few times.
Then proceed to click on the different states with left mouse button. On one of the clicks, both scripts reset to previous state.
You can even try this in your demos folder, the scripts will revert to their original form, always.

Here is the video:

https://www.youtube.com/watch?v=pauG65UpWAk

**Comment by Daylily-Zeleen** [comment] 2022-10-19 13:01
> 

I found it your `output` dock has some error print, please check it first.
I think it will print that the class `CScharpScript` is not exist.

Please use Godot mono version to try again. Or clone the latest repo to test( I fix this bug in v1.0).
(full version - v1.0 for Godot Marketplace is uploaded and reviewing.)

However, I think that can't found `CScharpScript` is not the reson for this bug.

I can't reproduce this bug even follow your video......

Here is my demo video:
[https://youtu.be/guCdThKPAIU](url)

**Comment by sh1ny** [comment] 2022-10-19 13:45
Hey,

Really puzzling, i will download 1.0 and give it a try.
Thank you!

**Comment by Daylily-Zeleen** [comment] 2022-10-20 02:47
> Hey,
> 
> Really puzzling, i will download 1.0 and give it a try. Thank you!

I will close this issue first.

If you meet this bug in v1.0, please continue reply in this issue, I will reopen it.

If you find out the reson of this bug is actual relate on this addon, please report to me or try to fix it then open a pr.

**Closed as completed by Daylily-Zeleen** 2022-10-20 02:47 UTC
